### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by rajesh99** [The-SaaS-Factory/next-14-saas-boilerplate#7]
https://next14.thesaasfactory.dev/en

Onboarding is not working

**Comment by RoylerMarichal** [comment]
![image](https://github.com/user-attachments/assets/9930f549-b4e3-450d-9270-2f379eeb5c94)
Thanks for letting me know. The problem was the limit of free Clerk organizations, I already deleted several manually and I plan to create a script as soon as possible to eliminate the oldest ones as new ones are created.

**Comment by sahin52** [comment]
When you click on sign in, even though you don't have an account, it seems like working but it throws error after onboarding

**Comment by RoylerMarichal** [comment]
> When you click on sign in, even though you don't have an account, it seems like working but it throws error after onboarding

Sorry, Clerk has a limit of 100 organizations in the free tier, and what's happening is that it fills up very quickly and I have to delete the test organizations. I'm going to automate this to delete the older organizations so that I don't have problems again.
